import { useAnimations, useGLTF } from "@react-three/drei";
import { useRef } from "react"

const Beach = (props)=>{
    const group = useRef();
    const {nodes, materials, animations} = useGLTF("/models-3d/beach.glb");
    const {actions} = useAnimations(animations,group);

    return (
        <group ref={group} position={[0, 0, 0]} rotation={[0, 0, 0]} scale={[1, 1, 1]} {...props} dispose={null}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boat_Wood_boat_0.geometry}
            material={materials.Wood_boat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boat_metal_part_Chimney_0.geometry}
            material={materials.Chimney}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Boat_rope_Rope_0.geometry}
            material={materials.Rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bottle_Glass_botlle_0.geometry}
            material={materials.Glass_botlle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bottle_Lable_0.geometry}
            material={materials.Lable}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bottle_in_water_Green_bottle_0.geometry}
            material={materials.Green_bottle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Bottle_in_water_Paper_0.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair_Wood_boat_0.geometry}
            material={materials.Wood_boat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chair001_Wood_boat_0.geometry}
            material={materials.Wood_boat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Chimney_Chimney_0.geometry}
            material={materials.Chimney}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Crate1_Wood_box_0.geometry}
            material={materials.Wood_box}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Crate2_Wood_box_0.geometry}
            material={materials.Wood_box}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Crate3_Wood_box_0.geometry}
            material={materials.Wood_box}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_Wooden_door_blue_0.geometry}
            material={materials.Wooden_door_blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_frame_Wood_darker_0.geometry}
            material={materials.Wood_darker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Door_handle_Door_handle_0.geometry}
            material={materials.Door_handle}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Fishing_net_Rope_0.geometry}
            material={materials.Rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.House_supports_Wood_darker_0.geometry}
            material={materials.Wood_darker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern_Glass_0.geometry}
            material={materials.Glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern_Lantern_metal_0.geometry}
            material={materials.Lantern_metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Lantern_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Main_support_poles_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_core_Palm_wood_light_0.geometry}
            material={materials.Palm_wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_core_Palm_wood_0.geometry}
            material={materials.Palm_wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_leafs_Palm_leaf_dark_0.geometry}
            material={materials.Palm_leaf_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_leafs_Palm_leaf_light_0.geometry}
            material={materials.Palm_leaf_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_leafs_Palm_leaf_medium_0.geometry}
            material={materials.Palm_leaf_medium}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_pot_Dirt_0.geometry}
            material={materials.Dirt}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_pot_Palm_pot_blue_0.geometry}
            material={materials.Palm_pot_blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Palm_pot_Palm_pot_white_0.geometry}
            material={materials.Palm_pot_white}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane001_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane002_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane003_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane004_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane005_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane006_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane008_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane009_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank001_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank002_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank003_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank004_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank005_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank006_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank007_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank008_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank009_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank010_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank011_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank012_Roof_dark_0.geometry}
            material={materials.Roof_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank013_Roof_dark_0.geometry}
            material={materials.Roof_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank014_Roof_dark_0.geometry}
            material={materials.Roof_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank015_Roof_medium_0.geometry}
            material={materials.Roof_medium}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank016_Roof_light_0.geometry}
            material={materials.Roof_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank017_Roof_dark_0.geometry}
            material={materials.Roof_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank018_Roof_medium_0.geometry}
            material={materials.Roof_medium}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank019_Roof_light_0.geometry}
            material={materials.Roof_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plank020_Wood_normal_0.geometry}
            material={materials.Wood_normal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_Roof_dark_0.geometry}
            material={materials.Roof_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_Roof_light_0.geometry}
            material={materials.Roof_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_Roof_medium_0.geometry}
            material={materials.Roof_medium}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Roof_beam_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rope_Rope_0.geometry}
            material={materials.Rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rope001_Rope_0.geometry}
            material={materials.Rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rope002_Rope_0.geometry}
            material={materials.Rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Rope003_Rope_0.geometry}
            material={materials.Rope}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sack1_Sack_0.geometry}
            material={materials.Sack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sack2_Sack_0.geometry}
            material={materials.Sack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sack3_Sack_0.geometry}
            material={materials.Sack}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sand_bottom_Sand_0.geometry}
            material={materials.Sand}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Small_window_support_Wood_dark_0.geometry}
            material={materials.Wood_dark}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Stool_Wood_boat_0.geometry}
            material={materials.Wood_boat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Table_Wood_boat_0.geometry}
            material={materials.Wood_boat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus_Chimney_0.geometry}
            material={materials.Chimney}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Towel1_Red_Cloth_0.geometry}
            material={materials.Red_Cloth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Towel2_White_cloth_0.geometry}
            material={materials.White_cloth}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_Walls_0.geometry}
            material={materials.Walls}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_2_Walls_0.geometry}
            material={materials.Walls}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_3_Walls_0.geometry}
            material={materials.Walls}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_4_Walls_0.geometry}
            material={materials.Walls}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_5_Walls_0.geometry}
            material={materials.Walls}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wall_6_Walls_0.geometry}
            material={materials.Walls}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Water_Water_0.geometry}
            material={materials.Water}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_blankets_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_blankets001_Wood_light_0.geometry}
            material={materials.Wood_light}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_circular_Circular_window_0.geometry}
            material={materials.Circular_window}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_circular_cover_Circular_window_0.geometry}
            material={materials.Circular_window}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_circular_cover001_Circular_window_0.geometry}
            material={materials.Circular_window}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_circular001_Circular_window_0.geometry}
            material={materials.Circular_window}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_frames_Wood_darker_0.geometry}
            material={materials.Wood_darker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Window_frames001_Wood_darker_0.geometry}
            material={materials.Wood_darker}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_support_1_Wooden_pole_inner_0.geometry}
            material={materials.Wooden_pole_inner}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_support_1_Wooden_pole_0.geometry}
            material={materials.Wooden_pole}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_support2_Wooden_pole_inner_0.geometry}
            material={materials.Wooden_pole_inner}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_support2_Wooden_pole_0.geometry}
            material={materials.Wooden_pole}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_support3_Wooden_pole_inner_0.geometry}
            material={materials.Wooden_pole_inner}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Wood_support3_Wooden_pole_0.geometry}
            material={materials.Wooden_pole}
          />
        </group>
      )
}

export default Beach;
useGLTF.preload("models-3d/beach.glb")